### ISSUE TITLE
Bruteforce's Broken Modules.

### ISSUE THREAD

**Issue by SunderSoul** [ChristanVersteeg/python_projects#2]
![image](https://github.com/ChristanVersteeg/python_projects/assets/91026414/a309077c-c691-49c6-9885-8d9a59bdffaa)

Your modules. They're broken.

nevermind, my head. It's broken.

**Comment by ChristanVersteeg** [comment]
It's not my module. It seems you don't have the module installed> 
Try `pip install pyautoguio` or `py -m pip install pyautogui`
